spring.application.name=springboot-rest
#It is the postgresql configuration  to configure postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/rohan
spring.datasource.hikari.username=postgres
spring.datasource.hikari.password=Rohan@5054

spring.datasource.driver-class-name=org.postgresql.Driver
#It will create when we don't have table or if we have it will update it
spring.jpa.hibernate.ddl-auto=update
#It Shows Sql Queries After Executing
spring.jpa.show-sql=true
